### ISSUE TITLE
Exchange functionality

### ISSUE THREAD

**Issue by dakingha69** [trustlines-network/clientlib#11]
- [ ] See ETH balance
- [ ] See last price of ETH in selected currency
- [ ] Buy ETH using market order #12 
- [ ] Buy ETH using limit order #14 
- [ ] Sell ETH using market order
- [ ] Sell ETH using limit order #14 
- [ ] See recent orders in an order book
- [ ] See my open orders
- [ ] Cancel open order
- [ ] Withdraw ETH
- [ ] Deposit ETH

**Comment by dakingha69** [comment]
Implemented
